apiVersion: apps/v1
kind: Deployment
metadata:
  name: preservedhub-backend
  namespace: preservedhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preservedhub-backend
  template:
    metadata:
      labels:
        app: preservedhub-backend
    spec:
      containers:
        - name: backend
          image: preservedhub-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/preservedhub"
            - name: JWT_SECRET
              value: "preservedhub_secret_devsecops"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: preservedhub
spec:
  selector:
    app: preservedhub-backend
  ports:
    - port: 4000
      targetPort: 4000
